# Generated by Django 6.0.3 on 2026-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('python', 'Python'), ('dbms', 'DBMS'), ('networking', 'Networking'), ('os', 'Operating Systems'), ('dsa', 'Data Structures')], max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
